// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2025-2026 Jörg Simbrig <Josbrig@simbrig.de>

#include <fidgen/generator.hpp>
#include <fidgen/version.hpp>

#include <ostream>
#include <sstream>
#include <string>

namespace fidgen {

// ─────────────────────────────────────────────────────────────────────────────
// Helper: emit a double literal in a way that round-trips faithfully
// ─────────────────────────────────────────────────────────────────────────────
static void wr(std::ostream& o, double v)  { o << fmt_double(v); }

// ─────────────────────────────────────────────────────────────────────────────
// C99Generator
// ─────────────────────────────────────────────────────────────────────────────
class C99Generator final : public Generator {
public:
    void generate(std::ostream& out,
                  const FilterDescriptor& f,
                  const GeneratorOptions& opts) const override;

private:
    void emit_scalar(std::ostream& out,
                     const FilterDescriptor& f,
                     const std::string& fn,
                     const std::string& tn) const;

    void emit_fir_scalar(std::ostream& out,
                         const FilterDescriptor& f,
                         const std::string& fn,
                         const std::string& tn) const;

    void emit_neon(std::ostream& out,
                   const FilterDescriptor& f,
                   const std::string& fn,
                   const std::string& tn) const;

    void emit_sse2(std::ostream& out,
                   const FilterDescriptor& f,
                   const std::string& fn,
                   const std::string& tn) const;

    void emit_avx2(std::ostream& out,
                   const FilterDescriptor& f,
                   const std::string& fn,
                   const std::string& tn) const;
};

// ── FIR scalar section ────────────────────────────────────────────────────────

void C99Generator::emit_fir_scalar(std::ostream& out,
                                    const FilterDescriptor& f,
                                    const std::string& fn,
                                    const std::string& tn) const
{
    const int N = f.n_taps();
    const int D = N - 1;   // delay-line length

    out << "/* SPDX-License-Identifier: GPL-2.0-or-later */\n"
        << "/* Generated by fidgen " << k_version << " */\n"
        << "/*\n"
        << " * Filter: " << fn << "\n"
        << " * Spec:   " << f.spec() << "\n"
        << " * Rate:   " << f.rate() << " Hz\n"
        << " * Taps:   " << N << "\n"
        << " * Gain:   "; wr(out, f.gain()); out << "\n"
        << " *\n"
        << " * FIR tapped delay line, fully unrolled.\n"
        << " * y[n] = h[0]*x[n] + h[1]*x[n-1] + ... + h[N-1]*x[n-N+1]\n"
        << " * (h[0] = most-recent tap; fidlib convention)\n"
        << " */\n\n";

    // ── State struct ──
    out << "typedef struct " << tn << "State {\n"
        << "    double s[" << D << "]; /* delay: s[0]=x[n-1], s[N-2]=x[n-N+1] */\n"
        << "} " << tn << "State;\n\n";

    // ── Coef struct ──
    out << "typedef struct " << tn << "Coef {\n"
        << "    double h[" << N << "];\n"
        << "    double gain;\n"
        << "} " << tn << "Coef;\n\n";

    // ── static const coefficient initializer ──
    out << "static const " << tn << "Coef " << fn << "_coef = {\n"
        << "    .h = {\n";
    for (int k = 0; k < N; ++k) {
        out << "        "; wr(out, f.taps()[static_cast<std::size_t>(k)]);
        out << (k < N - 1 ? "," : "") << "  /* h[" << k << "] */\n";
    }
    out << "    },\n"
        << "    .gain = "; wr(out, f.gain()); out << "\n"
        << "};\n\n";

    // ── reset ──
    out << "static inline void " << fn << "_reset(" << tn << "State *st)\n"
        << "{\n"
        << "    int i;\n"
        << "    for (i = 0; i < " << D << "; i++) st->s[i] = 0.0;\n"
        << "}\n\n";

    // ── step (fully unrolled MAC + shift) ──
    out << "static inline double " << fn << "_step("
        << tn << "State *st, const " << tn << "Coef *c, double x)\n"
        << "{\n"
        << "    double y = c->h[0] * x";
    for (int k = 1; k < N; ++k)
        out << "\n              + c->h[" << k << "] * st->s[" << (k - 1) << "]";
    out << ";\n";

    for (int k = D - 1; k > 0; --k)
        out << "    st->s[" << k << "] = st->s[" << (k - 1) << "];\n";
    if (D > 0)
        out << "    st->s[0] = x;\n";

    out << "    return c->gain * y;\n"
        << "}\n";
}

// ── scalar section ────────────────────────────────────────────────────────────

void C99Generator::emit_scalar(std::ostream& out,
                                const FilterDescriptor& f,
                                const std::string& fn,
                                const std::string& tn) const
{
    if (f.is_fir()) { emit_fir_scalar(out, f, fn, tn); return; }

    const int n  = f.n_stages();
    const int ns = f.n_slots();

    // ── SPDX + comment block ──
    out << "/* SPDX-License-Identifier: GPL-2.0-or-later */\n"
        << "/* Generated by fidgen " << k_version << " */\n"
        << "/*\n"
        << " * Filter: " << fn << "\n"
        << " * Spec:   " << f.spec() << "\n"
        << " * Rate:   " << f.rate() << " Hz\n"
        << " * Stages: " << n << "\n"
        << " * Gain:   "; wr(out, f.gain()); out << "\n"
        << " *\n"
        << " * Direct Form II, fully unrolled.\n"
        << " * w[n] = x - a1*w[n-1] - a2*w[n-2]   (a1,a2 stored with their natural sign)\n"
        << " * y[n] = b0*w[n] + b1*w[n-1] + b2*w[n-2]\n";
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        out << " * Stage " << i << ": b=[";
        wr(out,s.b[0]); out << ", "; wr(out,s.b[1]); out << ", "; wr(out,s.b[2]);
        out << "]  a=[1, ";
        wr(out,s.a[1]); out << ", "; wr(out,s.a[2]);
        out << "]\n";
    }
    out << " */\n\n";

    // ── State struct ──
    out << "typedef struct " << tn << "State {\n"
        << "    double s[" << ns << "]; /* delay line */\n"
        << "} " << tn << "State;\n\n";

    // ── Coef struct ──
    out << "typedef struct " << tn << "Coef {\n";
    for (int i = 0; i < n; ++i)
        out << "    double b0_" << i << ", b1_" << i << ", b2_" << i << ";\n"
            << "    double a1_" << i << ", a2_" << i << ";\n";
    out << "    double gain;\n"
        << "} " << tn << "Coef;\n\n";

    // ── static const coefficient initializer ──
    out << "static const " << tn << "Coef " << fn << "_coef = {\n";
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        out << "    /* stage " << i << " */\n"
            << "    .b0_" << i << " = "; wr(out,s.b[0]);
        out << ", .b1_" << i << " = "; wr(out,s.b[1]);
        out << ", .b2_" << i << " = "; wr(out,s.b[2]);
        out << ",\n    .a1_" << i << " = "; wr(out,s.a[1]);
        out << ", .a2_" << i << " = "; wr(out,s.a[2]);
        out << ",\n";
    }
    out << "    .gain = "; wr(out, f.gain());
    out << "\n};\n\n";

    // ── reset ──
    out << "static inline void " << fn << "_reset(" << tn << "State *st)\n"
        << "{\n"
        << "    int i;\n"
        << "    for (i = 0; i < " << ns << "; i++) st->s[i] = 0.0;\n"
        << "}\n\n";

    // ── step ──
    out << "static inline double " << fn << "_step("
        << tn << "State *st, const " << tn << "Coef *c, double x)\n{\n";

    int slot = 0;
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        const int s0 = slot, s1 = slot + 1;
        const std::string inp = (i == 0) ? "x" : ("y" + std::to_string(i - 1));

        if (s.order >= 2) {
            out << "    double w" << i << " = " << inp
                << " - c->a1_" << i << " * st->s[" << s0 << "]"
                << " - c->a2_" << i << " * st->s[" << s1 << "];\n"
                << "    double y" << i << " = c->b0_" << i << " * w" << i
                << " + c->b1_" << i << " * st->s[" << s0 << "]"
                << " + c->b2_" << i << " * st->s[" << s1 << "];\n"
                << "    st->s[" << s1 << "] = st->s[" << s0 << "];"
                << " st->s[" << s0 << "] = w" << i << ";\n";
            slot += 2;
        } else {
            out << "    double w" << i << " = " << inp
                << " - c->a1_" << i << " * st->s[" << s0 << "];\n"
                << "    double y" << i << " = c->b0_" << i << " * w" << i
                << " + c->b1_" << i << " * st->s[" << s0 << "];\n"
                << "    st->s[" << s0 << "] = w" << i << ";\n";
            slot += 1;
        }
    }
    if (n > 0)
        out << "    return c->gain * y" << (n-1) << ";\n";
    else
        out << "    return c->gain * x;\n";
    out << "}\n";
}

// ── NEON 2-channel parallel ───────────────────────────────────────────────────

void C99Generator::emit_neon(std::ostream& out,
                              const FilterDescriptor& f,
                              const std::string& fn,
                              const std::string& tn) const
{
    const int n = f.n_stages();

    out << "\n#if defined(__ARM_NEON)\n"
        << "#include <arm_neon.h>\n"
        << "/*\n"
        << " * " << fn << "_step_2ch_neon — 2-channel parallel (NEON float64x2_t)\n"
        << " * st[2]: state for channels 0 and 1\n"
        << " * x[2]:  input samples [ch0, ch1]\n"
        << " * y[2]:  output samples [ch0, ch1]\n"
        << " */\n"
        << "static inline void " << fn << "_step_2ch_neon(\n"
        << "    " << tn << "State st[2], const " << tn << "Coef *c,\n"
        << "    const double x[2], double y[2])\n"
        << "{\n"
        << "    float64x2_t xv = vld1q_f64(x);\n"
        << "    float64x2_t gain_v = vdupq_n_f64(c->gain);\n";

    // Declare SIMD output variable
    out << "    float64x2_t yv = xv; /* will hold cascade output */\n\n";

    int slot = 0;
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        const int s0 = slot, s1 = slot + 1;
        const std::string inv = (i == 0) ? "xv" : ("yv" + std::to_string(i-1));

        out << "    /* stage " << i << " */\n"
            << "    float64x2_t neon_s" << s0 << " = vcombine_f64(\n"
            << "        vld1_f64(&st[0].s[" << s0 << "]), vld1_f64(&st[1].s[" << s0 << "]));\n";
        if (s.order >= 2) {
            out << "    float64x2_t neon_s" << s1 << " = vcombine_f64(\n"
                << "        vld1_f64(&st[0].s[" << s1 << "]), vld1_f64(&st[1].s[" << s1 << "]));\n";
        }

        out << "    float64x2_t a1_" << i << "v = vdupq_n_f64(c->a1_" << i << ");\n";
        if (s.order >= 2)
            out << "    float64x2_t a2_" << i << "v = vdupq_n_f64(c->a2_" << i << ");\n";
        out << "    float64x2_t b0_" << i << "v = vdupq_n_f64(c->b0_" << i << ");\n"
            << "    float64x2_t b1_" << i << "v = vdupq_n_f64(c->b1_" << i << ");\n";
        if (s.order >= 2)
            out << "    float64x2_t b2_" << i << "v = vdupq_n_f64(c->b2_" << i << ");\n";

        if (s.order >= 2) {
            // w = inv - a1*s0 - a2*s1   using vfmsq: a - b*c = vfmsq(a, b, c)
            out << "    float64x2_t w" << i << " = vfmsq_f64(\n"
                << "        vfmsq_f64(" << inv << ", a1_" << i << "v, neon_s" << s0 << "),\n"
                << "        a2_" << i << "v, neon_s" << s1 << ");\n"
                // y = b0*w + b1*s0 + b2*s1  using vfmaq: a + b*c = vfmaq(a, b, c)
                << "    float64x2_t yv" << i << " = vfmaq_f64(\n"
                << "        vfmaq_f64(vmulq_f64(b0_" << i << "v, w" << i << "),\n"
                << "                  b1_" << i << "v, neon_s" << s0 << "),\n"
                << "        b2_" << i << "v, neon_s" << s1 << ");\n";
            // State update
            out << "    vst1_f64(&st[0].s[" << s1 << "], vget_low_f64(neon_s" << s0 << "));\n"
                << "    vst1_f64(&st[1].s[" << s1 << "], vget_high_f64(neon_s" << s0 << "));\n"
                << "    vst1_f64(&st[0].s[" << s0 << "], vget_low_f64(w" << i << "));\n"
                << "    vst1_f64(&st[1].s[" << s0 << "], vget_high_f64(w" << i << "));\n";
            slot += 2;
        } else {
            out << "    float64x2_t w" << i << " = vfmsq_f64(" << inv
                << ", a1_" << i << "v, neon_s" << s0 << ");\n"
                << "    float64x2_t yv" << i << " = vfmaq_f64("
                << "vmulq_f64(b0_" << i << "v, w" << i << "), "
                << "b1_" << i << "v, neon_s" << s0 << ");\n"
                << "    vst1_f64(&st[0].s[" << s0 << "], vget_low_f64(w" << i << "));\n"
                << "    vst1_f64(&st[1].s[" << s0 << "], vget_high_f64(w" << i << "));\n";
            slot += 1;
        }
        out << "\n";
    }

    const std::string last_yv = (n > 0) ? ("yv" + std::to_string(n-1)) : "xv";
    out << "    vst1q_f64(y, vmulq_f64(gain_v, " << last_yv << "));\n"
        << "}\n"
        << "#endif /* __ARM_NEON */\n";
}

// ── SSE2 2-channel parallel ───────────────────────────────────────────────────

void C99Generator::emit_sse2(std::ostream& out,
                              const FilterDescriptor& f,
                              const std::string& fn,
                              const std::string& tn) const
{
    const int n = f.n_stages();

    out << "\n#if defined(__SSE2__)\n"
        << "#include <emmintrin.h>\n"
        << "/* " << fn << "_step_2ch_sse2 — 2-channel parallel (__m128d) */\n"
        << "static inline void " << fn << "_step_2ch_sse2(\n"
        << "    " << tn << "State st[2], const " << tn << "Coef *c,\n"
        << "    const double x[2], double y[2])\n"
        << "{\n"
        << "    __m128d xv = _mm_loadu_pd(x);\n"
        << "    __m128d gain_v = _mm_set1_pd(c->gain);\n"
        << "    __m128d yv = xv;\n\n";

    int slot = 0;
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        const int s0 = slot, s1 = slot + 1;
        const std::string inv = (i == 0) ? "xv" : ("yv" + std::to_string(i-1));

        out << "    /* stage " << i << " */\n"
            << "    __m128d sse_s" << s0 << " = _mm_set_pd(st[1].s[" << s0
            << "], st[0].s[" << s0 << "]);\n";
        if (s.order >= 2)
            out << "    __m128d sse_s" << s1 << " = _mm_set_pd(st[1].s[" << s1
                << "], st[0].s[" << s1 << "]);\n";

        out << "    __m128d a1_" << i << "v = _mm_set1_pd(c->a1_" << i << ");\n";
        if (s.order >= 2)
            out << "    __m128d a2_" << i << "v = _mm_set1_pd(c->a2_" << i << ");\n";
        out << "    __m128d b0_" << i << "v = _mm_set1_pd(c->b0_" << i << ");\n"
            << "    __m128d b1_" << i << "v = _mm_set1_pd(c->b1_" << i << ");\n";
        if (s.order >= 2)
            out << "    __m128d b2_" << i << "v = _mm_set1_pd(c->b2_" << i << ");\n";

        if (s.order >= 2) {
            // SSE2 has no fma — use separate mul+sub
            out << "    __m128d w" << i << " = _mm_sub_pd(\n"
                << "        _mm_sub_pd(" << inv << ", _mm_mul_pd(a1_" << i << "v, sse_s" << s0 << ")),\n"
                << "        _mm_mul_pd(a2_" << i << "v, sse_s" << s1 << "));\n"
                << "    __m128d yv" << i << " = _mm_add_pd(\n"
                << "        _mm_add_pd(_mm_mul_pd(b0_" << i << "v, w" << i << "),\n"
                << "                   _mm_mul_pd(b1_" << i << "v, sse_s" << s0 << ")),\n"
                << "        _mm_mul_pd(b2_" << i << "v, sse_s" << s1 << "));\n";
            // State update via _mm_storeh_pd / _mm_storel_pd
            out << "    _mm_storel_pd(&st[0].s[" << s1 << "], sse_s" << s0 << ");\n"
                << "    _mm_storeh_pd(&st[1].s[" << s1 << "], sse_s" << s0 << ");\n"
                << "    _mm_storel_pd(&st[0].s[" << s0 << "], w" << i << ");\n"
                << "    _mm_storeh_pd(&st[1].s[" << s0 << "], w" << i << ");\n";
            slot += 2;
        } else {
            out << "    __m128d w" << i << " = _mm_sub_pd(" << inv
                << ", _mm_mul_pd(a1_" << i << "v, sse_s" << s0 << "));\n"
                << "    __m128d yv" << i << " = _mm_add_pd("
                << "_mm_mul_pd(b0_" << i << "v, w" << i << "), "
                << "_mm_mul_pd(b1_" << i << "v, sse_s" << s0 << "));\n"
                << "    _mm_storel_pd(&st[0].s[" << s0 << "], w" << i << ");\n"
                << "    _mm_storeh_pd(&st[1].s[" << s0 << "], w" << i << ");\n";
            slot += 1;
        }
        out << "\n";
    }

    const std::string last_yv = (n > 0) ? ("yv" + std::to_string(n-1)) : "xv";
    out << "    _mm_storeu_pd(y, _mm_mul_pd(gain_v, " << last_yv << "));\n"
        << "}\n"
        << "#endif /* __SSE2__ */\n";
}

// ── AVX2 4-channel parallel ───────────────────────────────────────────────────

void C99Generator::emit_avx2(std::ostream& out,
                              const FilterDescriptor& f,
                              const std::string& fn,
                              const std::string& tn) const
{
    const int n = f.n_stages();

    out << "\n#if defined(__AVX2__)\n"
        << "#include <immintrin.h>\n"
        << "/* " << fn << "_step_4ch_avx2 — 4-channel parallel (__m256d) */\n"
        << "static inline void " << fn << "_step_4ch_avx2(\n"
        << "    " << tn << "State st[4], const " << tn << "Coef *c,\n"
        << "    const double x[4], double y[4])\n"
        << "{\n"
        << "    __m256d xv = _mm256_loadu_pd(x);\n"
        << "    __m256d gain_v = _mm256_set1_pd(c->gain);\n"
        << "    __m256d yv = xv;\n\n";

    int slot = 0;
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        const int s0 = slot, s1 = slot + 1;
        const std::string inv = (i == 0) ? "xv" : ("yv" + std::to_string(i-1));

        out << "    /* stage " << i << " */\n"
            << "    __m256d avx_s" << s0 << " = _mm256_set_pd(\n"
            << "        st[3].s[" << s0 << "], st[2].s[" << s0
            << "], st[1].s[" << s0 << "], st[0].s[" << s0 << "]);\n";
        if (s.order >= 2)
            out << "    __m256d avx_s" << s1 << " = _mm256_set_pd(\n"
                << "        st[3].s[" << s1 << "], st[2].s[" << s1
                << "], st[1].s[" << s1 << "], st[0].s[" << s1 << "]);\n";

        out << "    __m256d a1_" << i << "v = _mm256_set1_pd(c->a1_" << i << ");\n";
        if (s.order >= 2)
            out << "    __m256d a2_" << i << "v = _mm256_set1_pd(c->a2_" << i << ");\n";
        out << "    __m256d b0_" << i << "v = _mm256_set1_pd(c->b0_" << i << ");\n"
            << "    __m256d b1_" << i << "v = _mm256_set1_pd(c->b1_" << i << ");\n";
        if (s.order >= 2)
            out << "    __m256d b2_" << i << "v = _mm256_set1_pd(c->b2_" << i << ");\n";

        if (s.order >= 2) {
            // AVX2 FMA: _mm256_fmadd_pd(a, b, c) = a*b + c,  _mm256_fnmadd_pd = -(a*b)+c
            out << "    __m256d w" << i << " = _mm256_fnmadd_pd(a1_" << i << "v, avx_s" << s0 << ",\n"
                << "        _mm256_fnmadd_pd(a2_" << i << "v, avx_s" << s1 << ", " << inv << "));\n"
                << "    __m256d yv" << i << " = _mm256_fmadd_pd(b0_" << i << "v, w" << i << ",\n"
                << "        _mm256_fmadd_pd(b1_" << i << "v, avx_s" << s0
                << ", _mm256_mul_pd(b2_" << i << "v, avx_s" << s1 << ")));\n";
            // Scatter state update (4 independent channels)
            for (int ch = 0; ch < 4; ++ch) {
                out << "    st[" << ch << "].s[" << s1 << "] = st[" << ch << "].s[" << s0 << "];\n";
            }
            out << "    { double tmp[4]; _mm256_storeu_pd(tmp, w" << i << ");\n"
                << "      for (int ch=0;ch<4;ch++) st[ch].s[" << s0 << "] = tmp[ch]; }\n";
            slot += 2;
        } else {
            out << "    __m256d w" << i << " = _mm256_fnmadd_pd(a1_" << i
                << "v, avx_s" << s0 << ", " << inv << ");\n"
                << "    __m256d yv" << i << " = _mm256_fmadd_pd(b0_" << i << "v, w" << i
                << ", _mm256_mul_pd(b1_" << i << "v, avx_s" << s0 << "));\n"
                << "    { double tmp[4]; _mm256_storeu_pd(tmp, w" << i << ");\n"
                << "      for (int ch=0;ch<4;ch++) st[ch].s[" << s0 << "] = tmp[ch]; }\n";
            slot += 1;
        }
        out << "\n";
    }

    const std::string last_yv = (n > 0) ? ("yv" + std::to_string(n-1)) : "xv";
    out << "    _mm256_storeu_pd(y, _mm256_mul_pd(gain_v, " << last_yv << "));\n"
        << "}\n"
        << "#endif /* __AVX2__ */\n";
}

// ── main generate entry point ─────────────────────────────────────────────────

void C99Generator::generate(std::ostream& out,
                             const FilterDescriptor& f,
                             const GeneratorOptions& opts) const
{
    const std::string fn = f.func_name();
    const std::string tn = to_type_name(fn);
    const std::string ug = to_upper(fn);

    if (opts.with_guard)
        out << "#ifndef " << ug << "_H\n"
            << "#define " << ug << "_H\n\n";

    emit_scalar(out, f, fn, tn);

    if (!f.is_fir()) {
        if (opts.simd == SimdLevel::Neon  || opts.simd == SimdLevel::Auto)
            emit_neon(out, f, fn, tn);
        if (opts.simd == SimdLevel::Sse2  || opts.simd == SimdLevel::Auto)
            emit_sse2(out, f, fn, tn);
        if (opts.simd == SimdLevel::Avx2  || opts.simd == SimdLevel::Auto)
            emit_avx2(out, f, fn, tn);
    } else if (opts.simd != SimdLevel::None) {
        out << "\n/* SIMD multi-channel variants are not generated for FIR filters. */\n";
    }

    if (opts.with_guard)
        out << "\n#endif /* " << ug << "_H */\n";
}

// ── registration (called from generator_factory.cpp) ─────────────────────────
std::unique_ptr<Generator> make_c99_generator() {
    return std::make_unique<C99Generator>();
}

} // namespace fidgen
