// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2025-2026 Jörg Simbrig <Josbrig@simbrig.de>

#include <fidgen/generator.hpp>
#include <fidgen/version.hpp>

#include <ostream>
#include <string>

namespace fidgen {

// ─────────────────────────────────────────────────────────────────────────────
// Cpp20Generator — emits a modern C++20 header-only filter
//
// Generated API:
//   class LpBu4Filter {
//       struct State { double s[N]; };
//       static constexpr Coef coef = { ... };
//       static void reset(State& st);
//       static double step(State& st, double x);
//   };
// ─────────────────────────────────────────────────────────────────────────────
class Cpp20Generator final : public Generator {
public:
    void generate(std::ostream& out,
                  const FilterDescriptor& f,
                  const GeneratorOptions& opts) const override;
};

void Cpp20Generator::generate(std::ostream& out,
                               const FilterDescriptor& f,
                               const GeneratorOptions& opts) const
{
    const std::string fn = f.func_name();
    const std::string tn = to_type_name(fn);
    const int n  = f.n_stages();
    const int ns = f.n_slots();

    if (opts.with_guard)
        out << "#pragma once\n";

    // ── FIR path ────────────────────────────────────────────────────────────
    if (f.is_fir()) {
        const int N = f.n_taps();
        const int D = N - 1;
        out << "// SPDX-License-Identifier: GPL-2.0-or-later\n"
            << "// Generated by fidgen " << k_version << "\n"
            << "//\n"
            << "// Filter : " << fn << " (FIR, " << N << " taps)\n"
            << "// Spec   : " << f.spec() << "\n"
            << "// Rate   : " << f.rate() << " Hz\n"
            << "// Gain   : " << fmt_double(f.gain()) << "\n"
            << "//\n"
            << "// FIR tapped delay line, fully unrolled.\n\n"
            << "#include <array>\n\n";

        out << "class " << tn << "Filter {\npublic:\n"
            << "    struct State { double s[" << D << "] = {}; };\n\n"
            << "    struct Coef  { double h[" << N << "]; double gain; };\n\n"
            << "    static constexpr Coef coef = {\n"
            << "        .h = {";
        for (int k = 0; k < N; ++k) {
            out << fmt_double(f.taps()[static_cast<std::size_t>(k)]);
            if (k < N-1) out << ", ";
        }
        out << "},\n"
            << "        .gain = " << fmt_double(f.gain()) << "\n"
            << "    };\n\n"
            << "    static void reset(State& st) noexcept { st = {}; }\n\n"
            << "    [[nodiscard]] static double step(State& st, double x) noexcept\n"
            << "    {\n"
            << "        double y = coef.h[0] * x";
        for (int k = 1; k < N; ++k)
            out << "\n                 + coef.h[" << k << "] * st.s[" << (k-1) << "]";
        out << ";\n";
        for (int k = D - 1; k > 0; --k)
            out << "        st.s[" << k << "] = st.s[" << (k-1) << "];\n";
        if (D > 0) out << "        st.s[0] = x;\n";
        out << "        return coef.gain * y;\n"
            << "    }\n"
            << "};\n";
        return;
    }

    // ── IIR path ─────────────────────────────────────────────────────────────
    out << "// SPDX-License-Identifier: GPL-2.0-or-later\n"
        << "// Generated by fidgen " << k_version << "\n"
        << "//\n"
        << "// Filter : " << fn << "\n"
        << "// Spec   : " << f.spec() << "\n"
        << "// Rate   : " << f.rate() << " Hz\n"
        << "// Stages : " << n << "\n"
        << "// Gain   : " << fmt_double(f.gain()) << "\n"
        << "//\n"
        << "// Direct Form II, fully unrolled.\n"
        << "// w[n] = x - a1*w[n-1] - a2*w[n-2]\n"
        << "// y[n] = b0*w[n] + b1*w[n-1] + b2*w[n-2]\n"
        << "//\n";
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        out << "// Stage " << i << " (order " << s.order << "):\n"
            << "//   b = [" << fmt_double(s.b[0]) << ", "
                            << fmt_double(s.b[1]) << ", "
                            << fmt_double(s.b[2]) << "]\n"
            << "//   a = [1, " << fmt_double(s.a[1]) << ", "
                                << fmt_double(s.a[2]) << "]\n";
    }
    out << "\n#include <array>\n#include <cstring>\n\n";

    out << "class " << tn << "Filter {\npublic:\n";

    out << "    struct State {\n"
        << "        double s[" << ns << "] = {};\n"
        << "    };\n\n";

    out << "    struct Coef {\n";
    for (int i = 0; i < n; ++i)
        out << "        double b0_" << i << ", b1_" << i << ", b2_" << i << ";\n"
            << "        double a1_" << i << ", a2_" << i << ";\n";
    out << "        double gain;\n"
        << "    };\n\n";

    out << "    static constexpr Coef coef = {\n";
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        out << "        /* stage " << i << " */\n"
            << "        ." << "b0_" << i << " = " << fmt_double(s.b[0]) << ",\n"
            << "        ." << "b1_" << i << " = " << fmt_double(s.b[1]) << ",\n"
            << "        ." << "b2_" << i << " = " << fmt_double(s.b[2]) << ",\n"
            << "        ." << "a1_" << i << " = " << fmt_double(s.a[1]) << ",\n"
            << "        ." << "a2_" << i << " = " << fmt_double(s.a[2]) << ",\n";
    }
    out << "        .gain = " << fmt_double(f.gain()) << "\n"
        << "    };\n\n";

    out << "    static void reset(State& st) noexcept\n"
        << "    {\n"
        << "        st = {};\n"
        << "    }\n\n";

    out << "    [[nodiscard]] static double step(State& st, double x) noexcept\n"
        << "    {\n";

    int slot = 0;
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        const int s0 = slot, s1 = slot + 1;
        const std::string inp = (i == 0) ? "x" : ("y" + std::to_string(i - 1));

        if (s.order >= 2) {
            out << "        const double w" << i << " = " << inp
                << " - coef.a1_" << i << " * st.s[" << s0 << "]"
                << " - coef.a2_" << i << " * st.s[" << s1 << "];\n"
                << "        const double y" << i << " = coef.b0_" << i << " * w" << i
                << " + coef.b1_" << i << " * st.s[" << s0 << "]"
                << " + coef.b2_" << i << " * st.s[" << s1 << "];\n"
                << "        st.s[" << s1 << "] = st.s[" << s0 << "];"
                << " st.s[" << s0 << "] = w" << i << ";\n";
            slot += 2;
        } else {
            out << "        const double w" << i << " = " << inp
                << " - coef.a1_" << i << " * st.s[" << s0 << "];\n"
                << "        const double y" << i << " = coef.b0_" << i << " * w" << i
                << " + coef.b1_" << i << " * st.s[" << s0 << "];\n"
                << "        st.s[" << s0 << "] = w" << i << ";\n";
            slot += 1;
        }
    }
    if (n > 0)
        out << "        return coef.gain * y" << (n-1) << ";\n";
    else
        out << "        return coef.gain * x;\n";

    out << "    }\n";
    out << "};\n";
}

// ── registration ─────────────────────────────────────────────────────────────
std::unique_ptr<Generator> make_cpp20_generator() {
    return std::make_unique<Cpp20Generator>();
}

} // namespace fidgen
