// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2025-2026 Jörg Simbrig <Josbrig@simbrig.de>

#include <fidgen/generator.hpp>
#include <fidgen/version.hpp>

#include <ostream>
#include <string>

namespace fidgen {

// ─────────────────────────────────────────────────────────────────────────────
// JuliaGenerator — emits Julia module
//
// Generated API:
//   mutable struct LpBu4State … end
//   function reset!(f::LpBu4State)
//   function step!(f::LpBu4State, x::Float64)::Float64
// ─────────────────────────────────────────────────────────────────────────────
class JuliaGenerator final : public Generator {
public:
    void generate(std::ostream& out,
                  const FilterDescriptor& f,
                  const GeneratorOptions& opts) const override;
};

void JuliaGenerator::generate(std::ostream& out,
                               const FilterDescriptor& f,
                               const GeneratorOptions& opts) const
{
    const std::string fn = f.func_name();
    const std::string tn = to_type_name(fn);
    const int n  = f.n_stages();
    const int ns = f.n_slots();

    (void)opts;

    out << "# SPDX-License-Identifier: GPL-2.0-or-later\n"
        << "# Generated by fidgen " << k_version << "\n"
        << "#\n"
        << "# Filter : " << fn << "\n"
        << "# Spec   : " << f.spec() << "\n"
        << "# Rate   : " << f.rate() << " Hz\n";

    // ── FIR path ─────────────────────────────────────────────────────────────
    if (f.is_fir()) {
        const int N = f.n_taps();
        const int D = N - 1;
        out << "# Taps   : " << N << "\n#\n"
            << "# FIR tapped delay line, fully unrolled.\n\n"
            << "const GAIN_" << to_upper(fn) << " = " << fmt_double(f.gain()) << "\n"
            << "const H_" << to_upper(fn) << " = (";
        for (int k = 0; k < N; ++k) {
            out << fmt_double(f.taps()[static_cast<std::size_t>(k)]);
            if (k < N-1) out << ", ";
        }
        out << ")\n\n"
            << "mutable struct " << tn << "State\n"
            << "    s::Vector{Float64}\n"
            << "    " << tn << "State() = new(zeros(Float64, " << D << "))\n"
            << "end\n\n"
            << "function reset!(f::" << tn << "State)::Nothing\n"
            << "    fill!(f.s, 0.0); nothing\n"
            << "end\n\n"
            << "function step!(f::" << tn << "State, x::Float64)::Float64\n"
            << "    s = f.s\n"
            << "    h = H_" << to_upper(fn) << "\n"
            << "    y = h[1] * x";   // Julia 1-indexed
        for (int k = 1; k < N; ++k)
            out << " +\n        h[" << (k+1) << "] * s[" << k << "]";
        out << "\n";
        for (int k = D; k > 1; --k)
            out << "    s[" << k << "] = s[" << (k-1) << "]\n";
        if (D > 0) out << "    s[1] = x\n";
        out << "    GAIN_" << to_upper(fn) << " * y\n"
            << "end\n";
        return;
    }

    // ── IIR path ─────────────────────────────────────────────────────────────
    out << "# Stages : " << n << "\n"
        << "# Gain   : " << fmt_double(f.gain()) << "\n"
        << "#\n# Direct Form II, fully unrolled.\n\n";

    out << "const SPEC_" << to_upper(fn) << " = \"" << f.spec() << "\"\n"
        << "const GAIN_" << to_upper(fn) << " = " << fmt_double(f.gain()) << "\n\n";

    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        out << "# Stage " << i << "\n"
            << "const B" << i << " = ("
            << fmt_double(s.b[0]) << ", "
            << fmt_double(s.b[1]) << ", "
            << fmt_double(s.b[2]) << ")\n"
            << "const A" << i << " = (1.0, "
            << fmt_double(s.a[1]) << ", "
            << fmt_double(s.a[2]) << ")\n";
    }
    out << "\n";

    out << "mutable struct " << tn << "State\n"
        << "    s::Vector{Float64}\n"
        << "    " << tn << "State() = new(zeros(Float64, " << ns << "))\n"
        << "end\n\n";

    out << "function reset!(f::" << tn << "State)::Nothing\n"
        << "    fill!(f.s, 0.0)\n"
        << "    nothing\n"
        << "end\n\n";

    out << "function step!(f::" << tn << "State, x::Float64)::Float64\n"
        << "    s = f.s\n";

    int slot = 0;
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        const int s0 = slot + 1;
        const int s1 = slot + 2;
        const std::string inp = (i == 0) ? "x" : ("y" + std::to_string(i - 1));

        if (s.order >= 2) {
            out << "    w" << i << " = " << inp
                << " - A" << i << "[2] * s[" << s0 << "]"
                << " - A" << i << "[3] * s[" << s1 << "]\n"
                << "    y" << i << " = B" << i << "[1] * w" << i
                << " + B" << i << "[2] * s[" << s0 << "]"
                << " + B" << i << "[3] * s[" << s1 << "]\n"
                << "    s[" << s1 << "] = s[" << s0 << "]\n"
                << "    s[" << s0 << "] = w" << i << "\n";
            slot += 2;
        } else {
            out << "    w" << i << " = " << inp
                << " - A" << i << "[2] * s[" << s0 << "]\n"
                << "    y" << i << " = B" << i << "[1] * w" << i
                << " + B" << i << "[2] * s[" << s0 << "]\n"
                << "    s[" << s0 << "] = w" << i << "\n";
            slot += 1;
        }
    }

    if (n > 0)
        out << "    GAIN_" << to_upper(fn) << " * y" << (n-1) << "\n";
    else
        out << "    GAIN_" << to_upper(fn) << " * x\n";

    out << "end\n";
}

// ── registration ─────────────────────────────────────────────────────────────
std::unique_ptr<Generator> make_julia_generator() {
    return std::make_unique<JuliaGenerator>();
}

} // namespace fidgen
