// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2025-2026 Jörg Simbrig <Josbrig@simbrig.de>

#include <fidgen/generator.hpp>
#include <fidgen/version.hpp>

#include <ostream>
#include <string>

namespace fidgen {

// ─────────────────────────────────────────────────────────────────────────────
// MatlabGenerator — emits MATLAB/Octave .m file
//
// Generates a function file with a persistent state vector.
// Compatible with both MATLAB R2016b+ and GNU Octave 6+.
// ─────────────────────────────────────────────────────────────────────────────
class MatlabGenerator final : public Generator {
public:
    void generate(std::ostream& out,
                  const FilterDescriptor& f,
                  const GeneratorOptions& opts) const override;
};

void MatlabGenerator::generate(std::ostream& out,
                                const FilterDescriptor& f,
                                const GeneratorOptions& opts) const
{
    const std::string fn = f.func_name();
    const int n  = f.n_stages();
    const int ns = f.n_slots();

    (void)opts;

    out << "% SPDX-License-Identifier: GPL-2.0-or-later\n"
        << "% Generated by fidgen " << k_version << "\n"
        << "%\n"
        << "% Filter : " << fn << "\n"
        << "% Spec   : " << f.spec() << "\n"
        << "% Rate   : " << f.rate() << " Hz\n";

    // ── FIR path ─────────────────────────────────────────────────────────────
    if (f.is_fir()) {
        const int N = f.n_taps();
        const int D = N - 1;
        out << "% Taps   : " << N << "\n%\n"
            << "% Usage:\n"
            << "%   y = " << fn << "(x)   % process scalar sample\n"
            << "%   " << fn << "([])       % reset filter state\n%\n"
            << "% FIR tapped delay line, fully unrolled.\n\n";

        out << "function y = " << fn << "(x)\n"
            << "    persistent s;\n"
            << "    if isempty(s), s = zeros(" << D << ", 1); end\n\n"
            << "    if isempty(x)\n"
            << "        s = zeros(" << D << ", 1); y = []; return;\n"
            << "    end\n\n"
            << "    h = [";
        for (int k = 0; k < N; ++k) {
            out << fmt_double(f.taps()[static_cast<std::size_t>(k)]);
            if (k < N-1) out << ", ";
        }
        out << "];\n"
            << "    gain = " << fmt_double(f.gain()) << ";\n\n"
            << "    y = h(1) * x";
        for (int k = 1; k < N; ++k)    // MATLAB 1-indexed
            out << " ...\n      + h(" << (k+1) << ") * s(" << k << ")";
        out << ";\n";
        for (int k = D; k > 1; --k)    // MATLAB 1-indexed, shift oldest first
            out << "    s(" << k << ") = s(" << (k-1) << ");\n";
        if (D > 0) out << "    s(1) = x;\n";
        out << "    y = gain * y;\n"
            << "end\n";
        return;
    }

    // ── IIR path ─────────────────────────────────────────────────────────────
    out << "% Stages : " << n << "\n"
        << "% Gain   : " << fmt_double(f.gain()) << "\n"
        << "%\n"
        << "% Usage:\n"
        << "%   y = " << fn << "(x)         % process scalar sample\n"
        << "%   " << fn << "([])             % reset filter state\n"
        << "%\n"
        << "% Direct Form II, fully unrolled.\n\n";

    out << "function y = " << fn << "(x)\n"
        << "    persistent s;\n"
        << "    if isempty(s)\n"
        << "        s = zeros(" << ns << ", 1);\n"
        << "    end\n\n"
        << "    % reset on empty input\n"
        << "    if isempty(x)\n"
        << "        s = zeros(" << ns << ", 1);\n"
        << "        y = [];\n"
        << "        return;\n"
        << "    end\n\n";

    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        out << "    % Stage " << i << "\n"
            << "    b0_" << i << " = " << fmt_double(s.b[0]) << ";\n"
            << "    b1_" << i << " = " << fmt_double(s.b[1]) << ";\n"
            << "    b2_" << i << " = " << fmt_double(s.b[2]) << ";\n"
            << "    a1_" << i << " = " << fmt_double(s.a[1]) << ";\n"
            << "    a2_" << i << " = " << fmt_double(s.a[2]) << ";\n";
    }
    out << "    gain = " << fmt_double(f.gain()) << ";\n\n";

    int slot = 0;
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        const int s0 = slot + 1;
        const int s1 = slot + 2;
        const std::string inp = (i == 0) ? "x" : ("y_" + std::to_string(i - 1));

        if (s.order >= 2) {
            out << "    w_" << i << " = " << inp
                << " - a1_" << i << " * s(" << s0 << ")"
                << " - a2_" << i << " * s(" << s1 << ");\n"
                << "    y_" << i << " = b0_" << i << " * w_" << i
                << " + b1_" << i << " * s(" << s0 << ")"
                << " + b2_" << i << " * s(" << s1 << ");\n"
                << "    s(" << s1 << ") = s(" << s0 << ");\n"
                << "    s(" << s0 << ") = w_" << i << ";\n";
            slot += 2;
        } else {
            out << "    w_" << i << " = " << inp
                << " - a1_" << i << " * s(" << s0 << ");\n"
                << "    y_" << i << " = b0_" << i << " * w_" << i
                << " + b1_" << i << " * s(" << s0 << ");\n"
                << "    s(" << s0 << ") = w_" << i << ";\n";
            slot += 1;
        }
        out << "\n";
    }

    if (n > 0)
        out << "    y = gain * y_" << (n-1) << ";\n";
    else
        out << "    y = gain * x;\n";

    out << "end\n";
}

// ── registration ─────────────────────────────────────────────────────────────
std::unique_ptr<Generator> make_matlab_generator() {
    return std::make_unique<MatlabGenerator>();
}

} // namespace fidgen
