// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2025-2026 Jörg Simbrig <Josbrig@simbrig.de>

#include <fidgen/generator.hpp>
#include <fidgen/version.hpp>

#include <ostream>
#include <string>

namespace fidgen {

// ─────────────────────────────────────────────────────────────────────────────
// PythonGenerator — emits a standalone Python class
//
// Generated API:
//   class LpBu4Filter:
//       def reset(self) -> None
//       def step(self, x: float) -> float
// ─────────────────────────────────────────────────────────────────────────────
class PythonGenerator final : public Generator {
public:
    void generate(std::ostream& out,
                  const FilterDescriptor& f,
                  const GeneratorOptions& opts) const override;
};

void PythonGenerator::generate(std::ostream& out,
                                const FilterDescriptor& f,
                                const GeneratorOptions& opts) const
{
    const std::string fn = f.func_name();
    const std::string tn = to_type_name(fn);
    const int n  = f.n_stages();
    const int ns = f.n_slots();

    out << "# SPDX-License-Identifier: GPL-2.0-or-later\n"
        << "# Generated by fidgen " << k_version << "\n"
        << "#\n"
        << "# Filter : " << fn << "\n"
        << "# Spec   : " << f.spec() << "\n"
        << "# Rate   : " << f.rate() << " Hz\n";

    // ── FIR path ─────────────────────────────────────────────────────────────
    if (f.is_fir()) {
        const int N = f.n_taps();
        const int D = N - 1;
        out << "# Taps   : " << N << "\n#\n"
            << "# FIR tapped delay line, fully unrolled.\n#\n\n";

        out << "_H_" << tn << " = (";
        for (int k = 0; k < N; ++k) {
            out << fmt_double(f.taps()[static_cast<std::size_t>(k)]);
            if (k < N-1) out << ", ";
        }
        out << ")\nGAIN_" << tn << " = " << fmt_double(f.gain()) << "\n\n\n";

        out << "class " << tn << "Filter:\n"
            << "    \"\"\"" << f.spec() << " FIR filter (" << f.rate() << " Hz, " << N << " taps)\"\"\"\n\n"
            << "    __slots__ = ('_s',)\n\n"
            << "    def __init__(self) -> None:\n"
            << "        self._s: list[float] = [0.0] * " << D << "\n\n"
            << "    def reset(self) -> None:\n"
            << "        for i in range(" << D << "):\n"
            << "            self._s[i] = 0.0\n\n"
            << "    def step(self, x: float) -> float:\n"
            << "        s = self._s\n"
            << "        h = _H_" << tn << "\n"
            << "        y = h[0] * x";
        for (int k = 1; k < N; ++k)
            out << " \\\n          + h[" << k << "] * s[" << (k-1) << "]";
        out << "\n";
        for (int k = D - 1; k > 0; --k)
            out << "        s[" << k << "] = s[" << (k-1) << "]\n";
        if (D > 0) out << "        s[0] = x\n";
        out << "        return GAIN_" << tn << " * y\n";

        if (opts.with_test) {
            out << "\n\nif __name__ == '__main__':\n"
                << "    _f = " << tn << "Filter()\n"
                << "    _x = 1.0\n"
                << "    for _ in range(512):\n"
                << "        print(f'{_f.step(_x):.17e}')\n"
                << "        _x = 0.0\n";
        }
        return;
    }

    // ── IIR path ─────────────────────────────────────────────────────────────
    out << "# Stages : " << n << "\n"
        << "# Gain   : " << fmt_double(f.gain()) << "\n"
        << "#\n"
        << "# Direct Form II, fully unrolled.\n"
        << "#\n\n";

    out << "SPEC_" << tn << " = '" << f.spec() << "'\n"
        << "GAIN_" << tn << " = " << fmt_double(f.gain()) << "\n\n";

    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        out << "# Stage " << i << "\n"
            << "_B" << i << " = ("
            << fmt_double(s.b[0]) << ", "
            << fmt_double(s.b[1]) << ", "
            << fmt_double(s.b[2]) << ")\n"
            << "_A" << i << " = (1.0, "
            << fmt_double(s.a[1]) << ", "
            << fmt_double(s.a[2]) << ")\n";
    }
    out << "\n\n";

    out << "class " << tn << "Filter:\n"
        << "    \"\"\"" << f.spec() << " digital filter (" << f.rate() << " Hz)\"\"\"\n\n"
        << "    __slots__ = ('_s',)\n\n"
        << "    def __init__(self) -> None:\n"
        << "        self._s: list[float] = [0.0] * " << ns << "\n\n"
        << "    def reset(self) -> None:\n"
        << "        for i in range(" << ns << "):\n"
        << "            self._s[i] = 0.0\n\n"
        << "    def step(self, x: float) -> float:\n"
        << "        s = self._s\n";

    int slot = 0;
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        const int s0 = slot, s1 = slot + 1;
        const std::string inp = (i == 0) ? "x" : ("y" + std::to_string(i - 1));

        if (s.order >= 2) {
            out << "        w" << i << " = " << inp
                << " - _A" << i << "[1] * s[" << s0 << "]"
                << " - _A" << i << "[2] * s[" << s1 << "]\n"
                << "        y" << i << " = _B" << i << "[0] * w" << i
                << " + _B" << i << "[1] * s[" << s0 << "]"
                << " + _B" << i << "[2] * s[" << s1 << "]\n"
                << "        s[" << s1 << "] = s[" << s0 << "]\n"
                << "        s[" << s0 << "] = w" << i << "\n";
            slot += 2;
        } else {
            out << "        w" << i << " = " << inp
                << " - _A" << i << "[1] * s[" << s0 << "]\n"
                << "        y" << i << " = _B" << i << "[0] * w" << i
                << " + _B" << i << "[1] * s[" << s0 << "]\n"
                << "        s[" << s0 << "] = w" << i << "\n";
            slot += 1;
        }
    }

    if (n > 0)
        out << "        return GAIN_" << tn << " * y" << (n-1) << "\n";
    else
        out << "        return GAIN_" << tn << " * x\n";

    if (opts.with_test) {
        out << "\n\nif __name__ == '__main__':\n"
            << "    _f = " << tn << "Filter()\n"
            << "    _x = 1.0\n"
            << "    for _ in range(512):\n"
            << "        print(f'{_f.step(_x):.17e}')\n"
            << "        _x = 0.0\n";
    }
}

// ── registration ─────────────────────────────────────────────────────────────
std::unique_ptr<Generator> make_python_generator() {
    return std::make_unique<PythonGenerator>();
}

} // namespace fidgen
