// SPDX-License-Identifier: GPL-2.0-or-later
// Copyright (C) 2025-2026 Jörg Simbrig <Josbrig@simbrig.de>

#include <fidgen/generator.hpp>
#include <fidgen/version.hpp>

#include <ostream>
#include <string>

namespace fidgen {

// ─────────────────────────────────────────────────────────────────────────────
// RustGenerator — emits a Rust module with a filter struct
//
// Generated API:
//   pub struct LpBu4State { s: [f64; N] }
//   impl LpBu4State {
//       pub fn new() -> Self
//       pub fn reset(&mut self)
//       pub fn step(&mut self, x: f64) -> f64
//   }
// ─────────────────────────────────────────────────────────────────────────────
class RustGenerator final : public Generator {
public:
    void generate(std::ostream& out,
                  const FilterDescriptor& f,
                  const GeneratorOptions& opts) const override;
};

void RustGenerator::generate(std::ostream& out,
                              const FilterDescriptor& f,
                              const GeneratorOptions& opts) const
{
    const std::string fn = f.func_name();
    const std::string sn = fn;
    const std::string tn = to_type_name(fn);
    const int n  = f.n_stages();
    const int ns = f.n_slots();

    out << "// SPDX-License-Identifier: GPL-2.0-or-later\n"
        << "// Generated by fidgen " << k_version << "\n"
        << "//\n"
        << "// Filter : " << fn << "\n"
        << "// Spec   : " << f.spec() << "\n"
        << "// Rate   : " << f.rate() << " Hz\n";

    // ── FIR path ─────────────────────────────────────────────────────────────
    if (f.is_fir()) {
        const int N = f.n_taps();
        const int D = N - 1;
        out << "// Taps   : " << N << "\n"
            << "//\n// FIR tapped delay line, fully unrolled.\n\n"
            << "#![allow(non_snake_case)]\n\n"
            << "pub const GAIN_" << to_upper(sn) << ": f64 = " << fmt_double(f.gain()) << "_f64;\n"
            << "const H_" << to_upper(sn) << ": [f64; " << N << "] = [";
        for (int k = 0; k < N; ++k) {
            out << fmt_double(f.taps()[static_cast<std::size_t>(k)]) << "_f64";
            if (k < N-1) out << ", ";
        }
        out << "];\n\n"
            << "pub struct " << tn << "State { s: [f64; " << D << "] }\n\n"
            << "impl " << tn << "State {\n"
            << "    pub fn new() -> Self { Self { s: [0.0_f64; " << D << "] } }\n"
            << "    pub fn reset(&mut self) { self.s = [0.0_f64; " << D << "]; }\n"
            << "    pub fn step(&mut self, x: f64) -> f64 {\n"
            << "        let h = &H_" << to_upper(sn) << ";\n"
            << "        let y = h[0] * x";
        for (int k = 1; k < N; ++k)
            out << "\n                 + h[" << k << "] * self.s[" << (k-1) << "]";
        out << ";\n";
        for (int k = D - 1; k > 0; --k)
            out << "        self.s[" << k << "] = self.s[" << (k-1) << "];\n";
        if (D > 0) out << "        self.s[0] = x;\n";
        out << "        GAIN_" << to_upper(sn) << " * y\n"
            << "    }\n"
            << "}\n\n"
            << "impl Default for " << tn << "State {\n"
            << "    fn default() -> Self { Self::new() }\n"
            << "}\n";

        if (opts.with_test) {
            out << "\nfn main() {\n"
                << "    let mut f = " << tn << "State::new();\n"
                << "    let mut x: f64 = 1.0_f64;\n"
                << "    for _i in 0..512_usize {\n"
                << "        println!(\"{:.17e}\", f.step(x));\n"
                << "        x = 0.0_f64;\n"
                << "    }\n"
                << "}\n";
        }
        return;
    }

    // ── IIR path ─────────────────────────────────────────────────────────────
    out << "// Stages : " << n << "\n"
        << "// Gain   : " << fmt_double(f.gain()) << "\n"
        << "//\n// Direct Form II, fully unrolled.\n\n"
        << "#![allow(non_snake_case)]\n\n";

    out << "pub const SPEC_" << to_upper(sn) << ": &str = \""
        << f.spec() << "\";\n"
        << "pub const GAIN_" << to_upper(sn) << ": f64 = "
        << fmt_double(f.gain()) << "_f64;\n\n";

    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        out << "// Stage " << i << "\n"
            << "const B" << i << ": [f64; 3] = ["
            << fmt_double(s.b[0]) << "_f64, "
            << fmt_double(s.b[1]) << "_f64, "
            << fmt_double(s.b[2]) << "_f64];\n"
            << "const A" << i << ": [f64; 3] = [1.0_f64, "
            << fmt_double(s.a[1]) << "_f64, "
            << fmt_double(s.a[2]) << "_f64];\n";
    }
    out << "\n";

    out << "pub struct " << tn << "State {\n"
        << "    s: [f64; " << ns << "],\n"
        << "}\n\n"
        << "impl " << tn << "State {\n"
        << "    pub fn new() -> Self {\n"
        << "        Self { s: [0.0_f64; " << ns << "] }\n"
        << "    }\n\n"
        << "    pub fn reset(&mut self) {\n"
        << "        self.s = [0.0_f64; " << ns << "];\n"
        << "    }\n\n"
        << "    pub fn step(&mut self, x: f64) -> f64 {\n";

    int slot = 0;
    for (int i = 0; i < n; ++i) {
        const auto& s = f.stages()[static_cast<std::size_t>(i)];
        const int s0 = slot, s1 = slot + 1;
        const std::string inp = (i == 0) ? "x" : ("y" + std::to_string(i - 1));

        if (s.order >= 2) {
            out << "        let w" << i << " = " << inp
                << " - A" << i << "[1] * self.s[" << s0 << "]"
                << " - A" << i << "[2] * self.s[" << s1 << "];\n"
                << "        let y" << i << " = B" << i << "[0] * w" << i
                << " + B" << i << "[1] * self.s[" << s0 << "]"
                << " + B" << i << "[2] * self.s[" << s1 << "];\n"
                << "        self.s[" << s1 << "] = self.s[" << s0 << "];\n"
                << "        self.s[" << s0 << "] = w" << i << ";\n";
            slot += 2;
        } else {
            out << "        let w" << i << " = " << inp
                << " - A" << i << "[1] * self.s[" << s0 << "];\n"
                << "        let y" << i << " = B" << i << "[0] * w" << i
                << " + B" << i << "[1] * self.s[" << s0 << "];\n"
                << "        self.s[" << s0 << "] = w" << i << ";\n";
            slot += 1;
        }
    }

    if (n > 0)
        out << "        GAIN_" << to_upper(sn) << " * y" << (n-1) << "\n";
    else
        out << "        GAIN_" << to_upper(sn) << " * x\n";

    out << "    }\n"
        << "}\n\n"
        << "impl Default for " << tn << "State {\n"
        << "    fn default() -> Self { Self::new() }\n"
        << "}\n";

    if (opts.with_test) {
        out << "\nfn main() {\n"
            << "    let mut f = " << tn << "State::new();\n"
            << "    let mut x: f64 = 1.0_f64;\n"
            << "    for _i in 0..512_usize {\n"
            << "        println!(\"{:.17e}\", f.step(x));\n"
            << "        x = 0.0_f64;\n"
            << "    }\n"
            << "}\n";
    }
}

// ── registration ─────────────────────────────────────────────────────────────
std::unique_ptr<Generator> make_rust_generator() {
    return std::make_unique<RustGenerator>();
}

} // namespace fidgen
