# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright (C) 2025-2026 Kai Dieki
# spv_to_header.cmake
# Usage: cmake -D INPUT=<spv> -D OUTPUT=<header> -P spv_to_header.cmake
# Converts a SPIR-V binary file to a C header with an embedded uint32_t array.

file(READ "${INPUT}" _spv_raw HEX)
string(LENGTH "${_spv_raw}" _hex_len)
math(EXPR _byte_count "${_hex_len} / 2")
math(EXPR _word_count "(${_byte_count} + 3) / 4")

# Build the array body as "0xXXXXXXXX, " chunks
set(_body "")
set(_col 0)
math(EXPR _last_word "${_word_count} - 1")
foreach(_i RANGE 0 ${_last_word})
    math(EXPR _byte0 "${_i} * 8")
    math(EXPR _byte1 "${_i} * 8 + 2")
    math(EXPR _byte2 "${_i} * 8 + 4")
    math(EXPR _byte3 "${_i} * 8 + 6")
    string(SUBSTRING "${_spv_raw}" ${_byte0} 2 _b0)
    string(SUBSTRING "${_spv_raw}" ${_byte1} 2 _b1)
    string(SUBSTRING "${_spv_raw}" ${_byte2} 2 _b2)
    string(SUBSTRING "${_spv_raw}" ${_byte3} 2 _b3)
    # SPIR-V is little-endian: byte0 is LSB
    string(APPEND _body "0x${_b3}${_b2}${_b1}${_b0}")
    if(NOT _i EQUAL _last_word)
        string(APPEND _body ", ")
    endif()
    math(EXPR _col "${_col} + 1")
    if(_col EQUAL 8 AND NOT _i EQUAL _last_word)
        string(APPEND _body "\n    ")
        set(_col 0)
    endif()
endforeach()

file(WRITE "${OUTPUT}"
"/* Auto-generated by spv_to_header.cmake — do not edit */
#ifndef FIR_DOT_SPV_H
#define FIR_DOT_SPV_H
#include <stdint.h>
static const uint32_t fir_dot_spv[] = {
    ${_body}
};
static const size_t fir_dot_spv_size = sizeof(fir_dot_spv);
#endif /* FIR_DOT_SPV_H */
")
message(STATUS "spv_to_header: ${_byte_count} bytes → ${_word_count} words → ${OUTPUT}")
